# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquinstudents.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: "My Portfolio"
email: "your-email@example.com"
description: "This is my portfolio site."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thaismfernandes.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: thaismfernandes

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

